#!/bin/bash
# MHEG2XMLTV - Tools
# Copyright (C) 2010-2016  Solorvox <solorvox@epic.geek.nz>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

BASE="$HOME/mheg/services"

if [ "$1" == "" ]; then
        echo "Usage: $0 \"Title search\"
	Prints all listings that have show titles that start with \"Title search\", case insenstive match.  "
        exit
fi

# Escape string
FIND=$(echo "$1" | sed 's|/|\\/|g')

# quick search full keyword search
for file in $(find $BASE -follow -wholename \*/data/\* -type f)
do
	# detail match on title only
	mhegview $file | awk -F\| "{ IGNORECASE=1; if ( \$8 ~ /^$FIND/) { print \$0 } }"
done

