#!/bin/bash
# MHEG2XMLTV - Tools
# Copyright (C) 2010-2016  Solorvox <solorvox@epic.geek.nz>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

if [ "$1" == "" ]; then
        echo "Usage: $0 \"show title\"
        Prints all CRID show ID numbers that match titles starting with \"show title\", case insenstive.
        Pattern matching is /^title/"
        exit
fi

mhegtitle "$1" | awk -F\| '{  for (i=10;i < NF;i++) { if ( ($i ~ /^\//) && ( $i !~ /\.png/) ) { gsub(/^\//, "", $i); print $i } } }' | sort | uniq 
